export const OpenCodeModels = {
  None: "",
  BigPickle: "big-pickle",
  Gpt4o: "gpt-4o",
  Gpt4oMini: "gpt-4o-mini",
  ClaudeSonnet35: "claude-3.5-sonnet",
  DeepseekChat: "deepseek-chat",
  DeepSeekV4FlashFree: "deepseek-v4-flash-free",
  MiMoV25Free: "mimo-v2.5-free",
  LagunaS21Free: "laguna-s-2.1-free",
  Ling30FlashFree: "ling-3.0-flash-free",
  NorthMiniCodeFree: "north-mini-code-free",
  Nemotron3UltraFree: "nemotron-3-ultra-free",
  Nemotron3SuperFree: "nemotron-3-super-free",
  MiniMaxM3: "minimax-m3",
  MiniMaxM27: "minimax-m2.7",
  MiniMaxM25: "minimax-m2.5",
  MiniMaxM25Free: "minimax-m2.5-free",
  GLM52: "glm-5.2",
  GLM51: "glm-5.1",
  KimiK25: "kimi-k2.5",
  KimiK26: "kimi-k2.6",
  KimiK2Thinking: "kimi-k2-thinking",
  KimiK2: "kimi-k2",
  Qwen3Coder480B: "qwen3-coder",
  Qwen36Plus: "qwen3.6-plus",
  Qwen35Plus: "qwen3.5-plus",
  Qwen37Max: "qwen3.7-max",
  Qwen37Plus: "qwen3.7-plus",
  GoGrok45: "opencode-go/grok-4.5",
  GoGLM52: "opencode-go/glm-5.2",
  GoGLM51: "opencode-go/glm-5.1",
  GoKimiK3: "opencode-go/kimi-k3",
  GoKimiK27Code: "opencode-go/kimi-k2.7-code",
  GoKimiK26: "opencode-go/kimi-k2.6",
  GoMiMoV25Pro: "opencode-go/mimo-v2.5-pro",
  GoMiMoV25: "opencode-go/mimo-v2.5",
  GoQwen37Max: "opencode-go/qwen3.7-max",
  GoQwen37Plus: "opencode-go/qwen3.7-plus",
  GoQwen36Plus: "opencode-go/qwen3.6-plus",
  GoMiniMaxM27: "opencode-go/minimax-m2.7",
  GoMiniMaxM3: "opencode-go/minimax-m3",
  GoDeepSeekV4Pro: "opencode-go/deepseek-v4-pro",
  GoDeepSeekV4Flash: "opencode-go/deepseek-v4-flash",
  GoHy3: "opencode-go/hy3",
} as const

export type OpenCodeModel = (typeof OpenCodeModels)[keyof typeof OpenCodeModels]

export const ShadcnModels = {
  None: "",
  Gpt4o: "gpt-4o",
  Gpt4oMini: "gpt-4o-mini",
  Gpt41: "gpt-4.1",
  ClaudeSonnet4: "claude-sonnet-4-20250514",
  ClaudeSonnet35: "claude-3.5-sonnet",
  ClaudeHaiku35: "claude-3.5-haiku",
  Gemini20Flash: "gemini-2.0-flash",
} as const

export type ShadcnModel = (typeof ShadcnModels)[keyof typeof ShadcnModels]

export const ZenModels = {
  None: "",
  BigPickle: "big-pickle",
  DeepSeekV4FlashFree: "deepseek-v4-flash-free",
  MiMoV25Free: "mimo-v2.5-free",
  LagunaS21Free: "laguna-s-2.1-free",
  Ling30TinyFree: "ling-3.0-tiny-free",
  LongCat20Free: "longcat-2.0-free",
  NorthMiniCodeFree: "north-mini-code-free",
  Nemotron3UltraFree: "nemotron-3-ultra-free",
  DeepSeekV4Pro: "deepseek-v4-pro",
  DeepSeekV4Flash: "deepseek-v4-flash",
  MiniMaxM3: "minimax-m3",
  MiniMaxM27: "minimax-m2.7",
  MiniMaxM25: "minimax-m2.5",
  GLM52: "glm-5.2",
  GLM51: "glm-5.1",
  GLM5: "glm-5",
  KimiK25: "kimi-k2.5",
  KimiK26: "kimi-k2.6",
  KimiK27Code: "kimi-k2.7-code",
  KimiK3: "kimi-k3",
} as const

export type ZenModel = (typeof ZenModels)[keyof typeof ZenModels]

export type AiPanelModel = OpenCodeModel | ShadcnModel | ZenModel

const MODEL_NAMES: Record<Exclude<AiPanelModel, "">, string> = {
  "gpt-4o": "GPT-4o",
  "gpt-4o-mini": "GPT-4o Mini",
  "gpt-4.1": "GPT-4.1",
  "claude-sonnet-4-20250514": "Claude Sonnet 4",
  "claude-3.5-sonnet": "Claude 3.5 Sonnet",
  "claude-3.5-haiku": "Claude 3.5 Haiku",
  "gemini-2.0-flash": "Gemini 2.0 Flash",
  "deepseek-chat": "DeepSeek Chat",
  "big-pickle": "Big Pickle",
  "deepseek-v4-flash-free": "DeepSeek V4 Flash Free",
  "mimo-v2.5-free": "MiMo-V2.5 Free",
  "laguna-s-2.1-free": "Laguna S 2.1 Free",
  "ling-3.0-tiny-free": "Ling-3.0 Tiny Free",
  "ling-3.0-flash-free": "Ling-3.0 Flash Free",
  "longcat-2.0-free": "LongCat-2.0 Free",
  "north-mini-code-free": "North Mini Code Free",
  "nemotron-3-ultra-free": "Nemotron 3 Ultra Free",
  "nemotron-3-super-free": "Nemotron 3 Super Free",
  "minimax-m3": "MiniMax M3",
  "minimax-m2.7": "MiniMax M2.7",
  "minimax-m2.5": "MiniMax M2.5",
  "minimax-m2.5-free": "MiniMax M2.5 Free",
  "deepseek-v4-pro": "DeepSeek V4 Pro",
  "deepseek-v4-flash": "DeepSeek V4 Flash",
  "kimi-k2.7-code": "Kimi K2.7 Code",
  "kimi-k3": "Kimi K3",
  "glm-5.2": "GLM 5.2",
  "glm-5.1": "GLM 5.1",
  "glm-5": "GLM 5",
  "kimi-k2.5": "Kimi K2.5",
  "kimi-k2.6": "Kimi K2.6",
  "kimi-k2-thinking": "Kimi K2 Thinking",
  "kimi-k2": "Kimi K2",
  "qwen3-coder": "Qwen3 Coder 480B",
  "qwen3.6-plus": "Qwen3.6 Plus",
  "qwen3.5-plus": "Qwen3.5 Plus",
  "qwen3.7-max": "Qwen3.7 Max",
  "qwen3.7-plus": "Qwen3.7 Plus",
  "opencode-go/grok-4.5": "Go · Grok 4.5",
  "opencode-go/glm-5.2": "Go · GLM 5.2",
  "opencode-go/glm-5.1": "Go · GLM 5.1",
  "opencode-go/kimi-k3": "Go · Kimi K3",
  "opencode-go/kimi-k2.7-code": "Go · Kimi K2.7 Code",
  "opencode-go/kimi-k2.6": "Go · Kimi K2.6",
  "opencode-go/mimo-v2.5-pro": "Go · MiMo-V2.5 Pro",
  "opencode-go/mimo-v2.5": "Go · MiMo-V2.5",
  "opencode-go/qwen3.7-max": "Go · Qwen3.7 Max",
  "opencode-go/qwen3.7-plus": "Go · Qwen3.7 Plus",
  "opencode-go/qwen3.6-plus": "Go · Qwen3.6 Plus",
  "opencode-go/minimax-m2.7": "Go · MiniMax M2.7",
  "opencode-go/minimax-m3": "Go · MiniMax M3",
  "opencode-go/deepseek-v4-pro": "Go · DeepSeek V4 Pro",
  "opencode-go/deepseek-v4-flash": "Go · DeepSeek V4 Flash",
  "opencode-go/hy3": "Go · Hy3",
}

export function modelDisplayName(model: string): string {
  if (!model) return ""
  return MODEL_NAMES[model as keyof typeof MODEL_NAMES] ?? model
}
