import type { AiPanelLabels } from "../types"

export const defaultLabels: AiPanelLabels = {
  title: "OneShot AI Panel",
  systemPrompt: "Prompt système",
  userPrompt: "Instructions supplémentaires",
  userPromptPlaceholder: "Instructions supplémentaires pour l'IA...",
  files: "Fichiers source",
  filesDescription: "Chaque fichier doit pointer vers un chemin absolu ou une URL (fichier local, CDN, serveur, drive...) que l'agent pourra consulter.",
  addFilePlaceholder: "Chemin ou URL du fichier...",
  addFileButton: "Ajouter",
  removeFile: "Retirer",
  tickets: "Tickets",
  ticketsDescription: "Les tickets décrivent les tâches concrètes à réaliser par l'agent. Chaque ticket peut avoir une description, une explication, et un schéma de réponse attendu. Un ticket marqué « fait » est exclu du prompt.",
  response: "Réponse IA",
  noPrompt: "Aucun prompt",
  noPromptDesc: "Définissez un prompt système pour guider l'IA",
  noFiles: "Aucun fichier",
  noFilesDesc: "Ajoutez des fichiers source (spécifications, schémas)",
  noTickets: "Aucun ticket",
  noTicketsDesc: "Ajoutez des tickets pour structurer les tâches de l'IA",
  noResponse: "Aucune réponse",
  noResponseDesc: "Cliquez sur « Générer » pour obtenir une réponse",
  generating: "Génération en cours...",
  cancel: "Annuler",
  actionLabel: "Générer",
  plugLabel: "Plugger",
  reasoning: "Raisonnement",
  status: "Statut",
  statusSystemPrompt: "Prompt système",
  statusUserPrompt: "Instructions supplémentaires",
  statusAdditionalContext: "Contexte additionnel",
  statusFiles: "Fichiers source",
  statusTickets: "Tickets",
  statusFeedback: "Erreurs de parsing",
  score: "Score",
  include: "Inclure",
  exclude: "Exclure",
  show: "Afficher",
  hide: "Masquer",
  showCurrentContent: "Afficher le contenu actuel",
  hideCurrentContent: "Masquer le contenu actuel",
  details: "Détails",
  responseSchema: "Schéma de réponse",
  error: "Erreur",
  provider: "Provider IA",
  configureProvider: "Configurer le provider",
  systemPromptPlaceholder: "Modifiez le prompt système...",
  additionalContext: "Contexte additionnel",
  additionalContextPlaceholder: "Ajoutez des informations contextuelles supplémentaires (extraits de code, logs, contraintes...)",
  viewPrompt: "Voir le prompt complet",
  copyPrompt: "Copier le prompt",
  promptCopied: "Prompt copié !",
  promptPreview: "Prompt complet assemblé",
  promptCharCount: "caractères",
  languageLabel: "Langue",
  languageDescription: "Langue d'affichage des libellés du panneau",
  settings: "Paramètres",
  selectProvider: "Provider IA",
  enableProvider: "Activé",
  disableProvider: "Désactivé",
  helpSection: "Aide",
  docLinks: "Documentation",
  modelLabel: "Modèle",
  modelPlaceholder: "Modèle (ex: gpt-4o)",
  modelNone: "Aucun",
  apiKeyLabel: "Clé API",
  apiKeyPlaceholder: "sk-...",
  baseUrlLabel: "URL de base",
  baseUrlPlaceholder: "https://...",
  promptSectionFiles: "--- Fichiers source ---",
  promptSectionTickets: "--- Tickets à traiter ---",
  promptSectionUserPrompt: "--- Instructions supplémentaires ---",
  promptSectionAdditionalContext: "--- Contexte additionnel ---",
  promptSectionFeedback: "--- Erreurs de la génération précédente ---",
  feedbackDescription:
    "Voici les erreurs de parsing de la réponse précédente. Évite de reproduire ces erreurs et respecte strictement le format de réponse demandé.",
  includeErrorsInPrompt: "Inclure les erreurs dans le prompt",
  ticketDescription: "Description",
  ticketExplanation: "Explication",
  ticketExistingContent: "Contenu existant",
  ticketNoExistingContent: "Aucun contenu pré-existant",
  ticketMissingSchema: "Schéma de réponse requis",
  noExistingContent: "Aucun contenu",
  noExistingContentDesc: "Ce ticket n'a pas encore de valeur",
  responseValid: "Format de réponse valide",
  responseInvalid: "Format de réponse invalide",
  responseFormatInstruction:
    "Réponds UNIQUEMENT en JSON : un tableau d'objets, un par ticket actif. Chaque objet doit avoir exactement une clé égale à la clé du ticket, et sa valeur doit respecter le schéma de réponse du ticket correspondant. Exemple : [ { \"cle-du-ticket\" : { ... } } ]",
  validationErrorNotJson: "La réponse n'est pas un JSON valide",
  validationErrorNotArray: "La réponse doit être un tableau d'objets",
  validationErrorKeyExpected: "Chaque élément doit avoir exactement une clé de ticket",
  validationErrorUnknownTicket: "Clé de ticket inconnue",
  validationErrorMissingTicket: "Réponse manquante pour le ticket",
  validationErrorSchema: "Ne respecte pas le schéma de réponse",
  errorNoStream: "Le handler n'a pas retourné de stream",
  errorUnknown: "Erreur inconnue",
  errorStreaming: "Erreur de streaming",
  infoButton: "Info",
  infoSheetTitle: "OneShot AI Panel",
  infoSheetDescription: "Assistant de génération piloté par IA : fichiers source, tickets à traiter, réponses JSON validées et boucle de correction.",
  infoOverviewTitle: "Vue d'ensemble",
  infoOverviewBody: "OneShot AI Panel est un générateur piloté par un modèle de langage. Vous décrivez l'objectif, fournissez des fichiers source et des tickets à traiter, puis le modèle génère une réponse JSON validée contre le schéma de chaque ticket.\n\nLa génération s'affiche en temps réel (streaming) avec le raisonnement du modèle, et la réponse est présentée en JSON indenté. Une revue compare ensuite chaque proposition au contenu existant avant intégration.\n\nLe panel est configurable (provider, modèle, langue) et entièrement localisable. Cette aide s'affiche dans la langue active.",
  infoPromptTitle: "Le prompt",
  infoPromptBody: "Le prompt est composé de trois zones :\n• Prompt système : le rôle et les règles du modèle (toujours envoyé).\n• Instructions supplémentaires : votre demande précise (optionnel).\n• Contexte additionnel : informations complémentaires (optionnel).\n\nLe bouton « Voir le prompt » affiche le message exact qui sera envoyé, et « Copier » permet de le réutiliser.",
  infoFilesTitle: "Les fichiers source",
  infoFilesBody: "Fournissez des fichiers ou des URLs (serveur, CDN, drive) que le modèle lira lui-même.\n\n• Un fichier est défini par un label et un chemin absolu ou une URL.\n• Inclure / Exclure active ou désactive un fichier dans le prompt.\n• Un fichier marqué « non présent » est simplement ignoré lors de l'envoi.\n• Le champ en bas de section ajoute un chemin ou une URL à la volée.\n\nLe panel ne convertit pas le contenu des fichiers : c'est le modèle qui les lit.",
  infoTicketsTitle: "Les tickets",
  infoTicketsBody: "Les tickets décrivent les tâches à accomplir. Chaque ticket top-level exige un schéma de réponse (JSON Schema) qui décrit le format attendu pour sa sortie.\n\n• Description : l'objectif du ticket.\n• Explication : la méthode à suivre.\n• Contenu existant : du contenu déjà présent à enrichir ou remplacer. Il est comparé à la proposition de l'IA dans la revue des modifications avant intégration.\n• Sous-tickets : découpage de la tâche en sous-étapes.\n\nUn ticket top-level sans schéma est signalé par un avertissement rouge.",
  infoValidationTitle: "Validation de la réponse",
  infoValidationBody: "Le modèle doit répondre UNIQUEMENT en JSON : un tableau d'objets, un par ticket actif, chacun au format { « clé-du-ticket » : valeur }. Chaque valeur doit respecter le schéma de réponse du ticket.\n\nÀ la fin de la génération, la réponse est validée automatiquement :\n• badge vert « Format de réponse valide » ;\n• badge rouge « Format de réponse invalide » avec le détail des erreurs par ticket.\n\nLa réponse affichée est automatiquement reformatée en JSON indenté (2 espaces) pour faciliter la lecture.\n\nLe mode de validation est configurable dans « Paramètres » :\n• Avertir : la génération reste possible, l'invalidité est simplement signalée.\n• Bloquer l'intégration : le bouton d'intégration reste désactivé tant que la réponse est invalide.\n\nDepuis le code, vous pouvez aussi fournir votre propre parseur (prop « parser ») pour contrôler entièrement la lecture de la réponse : il prend le pas sur la validation automatique.",
  infoFeedbackTitle: "Boucle de correction",
  infoFeedbackBody: "Quand la validation échoue, un bloc « Erreur » apparaît avec la liste détaillée des erreurs et une case « Inclure les erreurs dans le prompt ».\n\nEn relançant la génération, ces erreurs sont injectées dans le prompt pour dire au modèle ce qu'il doit éviter et lui rappeler le format attendu. Décochez la case pour relancer sans ce retour.",
  infoStatusTitle: "Statut & score",
  infoStatusBody: "La barre de statut résume l'état du panel : prompt système, instructions, contexte, fichiers, tickets et erreurs de parsing.\n\n• Vert : élément requis correctement fourni.\n• Orange : attention (aucun fichier présent).\n• Rouge : élément requis manquant.\n\nLe score global devient vert dès que tous les éléments requis sont fournis.",
  infoConfigTitle: "Provider & modèle",
  infoConfigBody: "Le bouton « Paramètres » ouvre la configuration du panel :\n• Langue de l'interface.\n• Provider (OpenCode, shadcn, HTTP générique) et son activation.\n• Modèle, clé API et URL de base selon le provider.",
  infoActionsTitle: "Actions",
  infoActionsBody: "En bas du panel :\n• « Voir le prompt » : aperçu complet du prompt qui sera envoyé.\n• « Générer » : lance la génération en streaming (devient « Annuler » en cours).\n• « Intégrer la sélection » : ouvre la revue des modifications (tickets cochés par défaut), compare chaque proposition au contenu existant et n'intègre que les tickets sélectionnés.",
  infoReviewTitle: "Revue des modifications",
  infoReviewBody: "Avant d'intégrer la réponse, le panel affiche une revue par ticket :\n• Chaque ticket est coché par défaut ; décochez ceux à exclure.\n• Le statut indique Identique, Modifié, Nouveau ou Supprimé.\n• Les changements sont listés (ajouts, suppressions, modifications) avec le chemin concerné.\n• Le bouton « Diffs » ouvre un dialogue côte à côte : contenu existant vs proposition, lignes numérotées, ajouts en vert et suppressions en rouge.\n• Les clés inconnues (sans ticket associé) sont affichées mais non cochées par défaut.\n\nLe bouton « Intégrer la sélection (n) » n'applique que les tickets cochés.",
  infoIntegrationTitle: "Intégration dans le code",
  infoIntegrationBody: "Le panel est un module React importable dans n'importe quel projet :\n• <OneShotAiPanel> : composant complet avec les props systemPrompt, files, tickets, invalidMode, parser, labels, language, adapter, onSend et onPlug.\n• onPlug(response, selectedKeys?) : reçoit la réponse et les clés cochées dans la revue (toutes si le paramètre est absent) ; appelez-le sans l'UI pour intégrer la réponse complète.\n• useAiPanel() : hook headless pour piloter la génération sans l'UI (envoi du prompt, parsing, validation, streaming).\n• Revue des modifications : avant l'intégration, le panel compare chaque ticket au contenu existant (statut Identique / Modifié / Nouveau / Supprimé) et propose un dialogue « Diffs » côte à côte.\n• parser : fournissez votre propre fonction de parsing, prioritaire sur la validation automatique par schéma.\n• invalidMode : « warn » (avertit) ou « block » (désactive l'intégration tant que la réponse est invalide).\n• showInfoIntegration / showInfoCredits / showInfoButton / showSettingsButton : masquer les blocs d'aide ou les boutons « Info » et « Paramètres » ; sans l'UI, la configuration (language, adapter, invalidMode) passe par les props.\n• Adapters : OpenCode, shadcn et HTTP générique sont fournis ; register() permet d'ajouter vos propres providers.\n• labels : toutes les chaînes UI sont surchargeables (fr / en / par défaut) pour une localisation complète.",
  infoCreditsTitle: "Crédits",
  infoCreditsBody: "OneShot AI Panel est un composant React open source, conçu pour être réutilisé dans vos projets. Consultez la landing page et le dépôt GitHub pour la documentation complète, les exemples et les versions.",
  infoCreditsLandingLabel: "Landing page",
  infoCreditsGithubLabel: "Dépôt GitHub",
  invalidModeLabel: "Mode de validation",
  invalidModeDescription: "Comportement quand la réponse ne respecte pas les schémas de tickets.",
  invalidModeWarn: "Avertir",
  invalidModeBlock: "Bloquer l'intégration",
  reviewTitle: "Vérification des modifications",
  reviewDescription: "Compare la réponse de l'IA avec le contenu existant avant de l'intégrer.",
  diffIdentical: "Identique",
  diffModified: "Modifié",
  diffAdded: "Nouveau",
  diffRemoved: "Supprimé",
  diffSelectAll: "Tout cocher",
  diffDeselectAll: "Tout décocher",
  diffNoChanges: "Aucun changement",
  diffUnknownTicket: "Clé inconnue",
  diffEmptyValue: "(vide)",
  diffInclude: "Inclure ce ticket",
  plugSelected: "Intégrer la sélection",
  diffViewFull: "Diffs",
  diffExisting: "Existant",
  diffProposed: "Proposé",
  diffClose: "Fermer",
  questionTitle: "Question de l'IA",
  questionDescription: "L'IA a besoin d'une précision pour continuer.",
  questionAnswer: "Répondre",
  questionSkip: "Ignorer",
  questionCustomPlaceholder: "Autre réponse (texte libre)...",
  permissionTitle: "Autorisation requise",
  permissionDescription: "Le modèle demande une autorisation pour continuer.",
  permissionAllowOnce: "Autoriser une fois",
  permissionAlways: "Toujours autoriser",
  permissionDeny: "Refuser",
  toolActivity: "Outil",
  context: "Contexte",
  contextDescription: "Session OpenCode partagée entre les panneaux. Elle est conservée dans un cookie et réutilisée, sauf si elle n'existe plus (recréée automatiquement).",
  statusSession: "Session",
  statusModel: "Modèle",
  statusTokens: "Tokens",
  statusCost: "Coût",
  sessionRenew: "Nouvelle session",
  sessionRenewDescription: "Supprime la session courante et démarre une nouvelle session.",
  statusConnecting: "Connexion au serveur OpenCode…",
  statusWaiting: "En attente du modèle…",
  statusStalled: "La génération semble bloquée. Vérifie que le serveur OpenCode est toujours actif.",
  statusTool: "En attente du serveur (outil en cours / autorisation…)",
}
