#!/usr/bin/env node

import { cpSync, existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join, relative, resolve } from "node:path"
import { spawnSync } from "node:child_process"

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const MODULE_SRC = join(PACKAGE_ROOT, "src", "module")
const PRIMITIVES_SRC = join(PACKAGE_ROOT, "src", "primitives")
const THEME_SRC = join(PACKAGE_ROOT, "themes", "globals.css")
const NEXT_PROXY_SRC = join(PACKAGE_ROOT, "src", "next-proxy")

const REQUIRED_PRIMITIVES = [
  "badge.tsx",
  "button.tsx",
  "checkbox.tsx",
  "dialog.tsx",
  "empty.tsx",
  "input.tsx",
  "label.tsx",
  "select.tsx",
  "sheet.tsx",
  "switch.tsx",
  "textarea.tsx",
]

const RUNTIME_DEPS = [
  "@base-ui/react",
  "@opencode-ai/sdk",
  "class-variance-authority",
  "clsx",
  "lucide-react",
  "tailwind-merge",
  "zod",
  "tw-animate-css",
]

const SHADCN_REGISTRY = "bn-dev-19/one-shot-ai-panel"

const VITE_ZEN_PROXY_SNIPPET = `// one-shot-ai-panel — OpenCode Zen dev-server proxy (Vite).
// Generated by \`one-shot-ai-panel install\`. Wire it into your vite.config.* :
//   import zenProxy from "./vite.zen-proxy.mjs"
//   export default defineConfig({ server: { proxy: { ...zenProxy } } })
// Production: route /api/zen to your backend (CORS + API keys must stay server-side).

export default {
  "/api/zen": {
    target: "https://opencode.ai",
    changeOrigin: true,
    rewrite: (path) => path.replace(/^\\/api\\/zen/, "/zen"),
  },
}
`

function log(icon, msg) {
  process.stdout.write(`${icon} ${msg}\n`)
}

function help() {
  process.stdout.write(
    `one-shot-ai-panel install — Integrates OneShotAiPanel into your React/Next.js or Vite project.

Usage:
  one-shot-ai-panel install [dir] [options]

Options:
  dir              Target project directory (default: current directory)
  --force          Overwrite existing files (module, primitives)
  --no-install     Do not install runtime dependencies
  --no-css         Do not modify the target project's globals.css
  --no-registry    Always copy primitives directly, even when components.json is detected
  --pm <pm>        Package manager: pnpm | npm | yarn | bun (default: auto-detected)
  --module-dir <d> Destination subdirectory for the module (default: src/external-modules/ai-panel)
  --module-only    Only copy/update the module source (keep ui/*, css and deps untouched)
  --no-proxy       Do not generate the OpenCode Zen same-origin proxy (Next route / Vite snippet)
  --help           Show this help

When the target project has a components.json (shadcn), the panel primitives
are added via the shadcn registry (npx shadcn add bn-dev-19/one-shot-ai-panel/<item>)
so you get the native skip/overwrite prompts. Otherwise they are copied directly.
`
  )
}

function parseArgs(argv) {
  const args = { dir: process.cwd(), force: false, noInstall: false, noCss: false, noRegistry: false, pm: null, moduleDir: "src/external-modules/ai-panel", moduleOnly: false, noProxy: false }
  const rest = [...argv]
  if (rest[0] === "install") rest.shift()
  while (rest.length) {
    const a = rest.shift()
    if (a === "--help" || a === "-h") {
      args.help = true
    } else if (a === "--force") {
      args.force = true
    } else if (a === "--no-install") {
      args.noInstall = true
    } else if (a === "--no-css") {
      args.noCss = true
    } else if (a === "--no-registry") {
      args.noRegistry = true
    } else if (a === "--pm") {
      args.pm = rest.shift()
    } else if (a === "--module-dir") {
      args.moduleDir = rest.shift()
    } else if (a === "--module-only") {
      args.moduleOnly = true
    } else if (a === "--no-proxy") {
      args.noProxy = true
    } else if (a.startsWith("-")) {
      process.stderr.write(`Unknown option: ${a}\n`)
      help()
      process.exit(1)
    } else {
      args.dir = resolve(a)
    }
  }
  return args
}

function detectPackageManager(target) {
  if (existsSync(join(target, "pnpm-lock.yaml"))) return "pnpm"
  if (existsSync(join(target, "bun.lockb")) || existsSync(join(target, "bun.lock"))) return "bun"
  if (existsSync(join(target, "yarn.lock"))) return "yarn"
  if (existsSync(join(target, "package-lock.json"))) return "npm"
  return "pnpm"
}

function detectFramework(target) {
  const files = readdirSync(target)
  const has = (...names) => names.some((n) => files.includes(n))
  if (has("next.config.ts", "next.config.mjs", "next.config.js", "next.config.mts", "next.config.cjs")) return "next"
  if (has("vite.config.ts", "vite.config.mjs", "vite.config.js", "vite.config.mts")) return "vite"
  return null
}

function checkAlias(target, framework, warnings) {
  const tsconfigPath = join(target, "tsconfig.json")
  let hasPathAlias = false
  if (existsSync(tsconfigPath)) {
    try {
      const paths = JSON.parse(readFileSync(tsconfigPath, "utf8")).compilerOptions?.paths
      hasPathAlias = !!(paths && paths["@/*"])
    } catch {
      /* ignore unreadable tsconfig */
    }
  }

  if (framework === "next") {
    if (!hasPathAlias) {
      warnings.push(
        `tsconfig.json: no "@/*" path alias found. The panel imports "@/" (module + primitives).\n` +
          `  Add to tsconfig.json: "compilerOptions": { "baseUrl": ".", "paths": { "@/*": ["./src/*"] } }`
      )
    }
    return
  }

  if (framework === "vite") {
    const viteConfig = ["vite.config.ts", "vite.config.mjs", "vite.config.js", "vite.config.mts"]
      .map((f) => join(target, f))
      .find((p) => existsSync(p))
    let hasViteAlias = false
    if (viteConfig) {
      const content = readFileSync(viteConfig, "utf8")
      hasViteAlias = /\balias\s*:/.test(content) && /['"]@['"]/.test(content)
    }
    if (!hasViteAlias) {
      warnings.push(
        `vite.config: no "@" alias found. The panel imports "@/components/ui/*" and "@/lib/utils".\n` +
          `  Add to vite.config.*: resolve: { alias: { "@": fileURLToPath(new URL("./src", import.meta.url)) } }\n` +
          `  (import fileURLToPath from "node:url"; add "@types/node" to devDependencies)`
      )
    }
    if (!hasPathAlias) {
      warnings.push(
        `tsconfig.json: no "@/*" path alias found (for editor/typecheck).\n` +
          `  Add to tsconfig.json: "compilerOptions": { "baseUrl": ".", "paths": { "@/*": ["./src/*"] } }`
      )
    }
  }
}

function checkTailwind(cssPath, warnings) {
  if (!cssPath) return
  const css = readFileSync(cssPath, "utf8")
  if (css.includes('@import "tailwindcss"')) return
  warnings.push(
    `Tailwind CSS v4 not detected in the stylesheet. The panel is styled with Tailwind classes — nothing will render without it.\n` +
      `  Add "tailwindcss" + "@tailwindcss/vite" (Vite) or "@tailwindcss/postcss" (Next) and import "tailwindcss" at the top of your stylesheet.`
  )
}

function findGlobalsCss(target) {
  const candidates = [
    join(target, "src", "app", "globals.css"),
    join(target, "app", "globals.css"),
    join(target, "src", "globals.css"),
    join(target, "globals.css"),
    join(target, "src", "index.css"),
    join(target, "index.css"),
  ]
  return candidates.find((p) => existsSync(p))
}

function themeBlock() {
  if (!existsSync(THEME_SRC)) return ""
  const css = readFileSync(THEME_SRC, "utf8")
  const start = css.indexOf("@theme inline")
  const end = css.indexOf("@layer base")
  if (start === -1 || end === -1) return ""
  return css.slice(start, end).trimEnd() + "\n"
}

function patchGlobalsCss(target, force) {
  const globals = findGlobalsCss(target)
  if (!globals) {
    log("⚠️", `No stylesheet found (looked for globals.css / index.css). Copy ${relative(target, THEME_SRC)} into your project or apply the theme manually.`)
    return null
  }
  let css = readFileSync(globals, "utf8")
  const changed = []

  if (!css.includes("tw-animate-css")) {
    if (css.includes('@import "tailwindcss";')) {
      css = css.replace('@import "tailwindcss";', '@import "tailwindcss";\n@import "tw-animate-css";')
    } else if (css.startsWith("@import")) {
      css = css.replace(/^@import[^\n]*\n/, '@import "tw-animate-css";\n')
    } else {
      css = `@import "tw-animate-css";\n${css}`
    }
    changed.push("tw-animate-css import")
  }

  if (!css.includes("--background:")) {
    const block = themeBlock()
    if (block) {
      css = `${css.trimEnd()}\n\n${block}\n`
      changed.push("shadcn theme tokens")
    }
  }

  if (changed.length) {
    writeFileSync(globals, css)
    log("✓", `${relative(target, globals)}: added ${changed.join(", ")}`)
  } else {
    log("•", `${relative(target, globals)}: already compatible (tw-animate-css + theme tokens present)`)
  }
  return globals
}

function copyFile(src, dest, force, root) {
  const display = root ? join("src", relative(join(root, "src"), dest)) : relative(process.cwd(), dest)
  if (existsSync(dest) && !force) {
    log("•", `skipped (already exists): ${display}`)
    return false
  }
  mkdirSync(dirname(dest), { recursive: true })
  cpSync(src, dest)
  log("✓", `created: ${display}`)
  return true
}

function installModule(target, force) {
  const dest = join(target, args.moduleDir)
  if (existsSync(dest)) {
    if (force) {
      cpSync(MODULE_SRC, dest, { recursive: true, force: true })
      log("✓", `${args.moduleDir}: reinstalled (--force)`)
    } else {
      log("•", `skipped (already exists): ${args.moduleDir} (use --force to reinstall)`)
    }
  } else {
    mkdirSync(dirname(dest), { recursive: true })
    cpSync(MODULE_SRC, dest, { recursive: true })
    log("✓", `module copied into ${args.moduleDir}`)
  }
}

function findAppDir(target) {
  for (const d of ["src/app", "app"]) {
    if (existsSync(join(target, d))) return d
  }
  return null
}

function installZenProxy(target, force) {
  if (args.noProxy) {
    log("•", "Zen same-origin proxy skipped (--no-proxy)")
    return false
  }
  const framework = detectFramework(target)

  if (framework === "next") {
    const appDir = findAppDir(target)
    if (!appDir) {
      log("•", "Zen proxy skipped — no app/ directory detected (Next.js App Router expected)")
      return false
    }
    const routeFile = join(target, appDir, "api", "zen", "v1", "[...path]", "route.ts")
    if (existsSync(routeFile) && !force) {
      log("•", `skipped (already exists): ${relative(target, routeFile)} (use --force to regenerate)`)
      return false
    }
    mkdirSync(dirname(routeFile), { recursive: true })
    cpSync(join(NEXT_PROXY_SRC, "zen.ts"), routeFile)
    log("✓", `generated Zen proxy: ${relative(target, routeFile)}`)
    return true
  }

  if (framework === "vite") {
    const snippet = join(target, "vite.zen-proxy.mjs")
    if (existsSync(snippet) && !force) {
      log("•", `skipped (already exists): ${relative(target, snippet)}`)
      return false
    }
    writeFileSync(snippet, VITE_ZEN_PROXY_SNIPPET)
    log("✓", `generated Zen dev proxy: ${relative(target, snippet)}`)
    return true
  }

  log("•", "Zen same-origin proxy skipped — unsupported framework (Next.js or Vite required)")
  return false
}

function detectShadcn(target) {
  return existsSync(join(target, "components.json"))
}

function shadcnRegistryItems() {
  return [...REQUIRED_PRIMITIVES.map((f) => f.replace(/\.tsx$/, "")), "loading-button"]
}

function hasLocalShadcn(target) {
  const binDir = join(target, "node_modules", ".bin")
  if (!existsSync(binDir)) return false
  try {
    return readdirSync(binDir).some((f) => f.startsWith("shadcn"))
  } catch {
    return false
  }
}

function shadcnRunner(pm, target) {
  if (hasLocalShadcn(target)) {
    switch (pm) {
      case "npm":
        return ["npx", "shadcn"]
      case "yarn":
        return ["yarn", "exec", "shadcn"]
      case "bun":
        return ["bunx", "shadcn"]
      default:
        return ["pnpm", "exec", "shadcn"]
    }
  }
  switch (pm) {
    case "npm":
      return ["npx", "--yes", "shadcn@latest"]
    case "yarn":
      return ["yarn", "dlx", "shadcn@latest"]
    case "bun":
      return ["bunx", "shadcn@latest"]
    default:
      return ["pnpm", "dlx", "shadcn@latest"]
  }
}

function installPrimitivesViaRegistry(target, force) {
  const pm = detectPackageManager(target)
  const local = hasLocalShadcn(target)
  if (!local) log("⏳", "first run downloads the shadcn CLI — this can take a moment (only the first time)")
  const cmd = [...shadcnRunner(pm, target), "add", ...shadcnRegistryItems().map((i) => `${SHADCN_REGISTRY}/${i}`)]
  if (force) cmd.push("--overwrite")
  log("⇣", `components.json detected — adding primitives via the shadcn registry${local ? " (using the project's shadcn)" : ""}:`)
  log("", `  ${cmd.join(" ")}`)
  const res = spawnSync(cmd[0], cmd.slice(1), { cwd: target, stdio: "inherit", shell: process.platform === "win32" })
  return res.status === 0
}

function installPrimitives(target, force, viaRegistry) {
  if (viaRegistry) {
    if (installPrimitivesViaRegistry(target, force)) {
      log("✓", "primitives installed via the shadcn registry (skip/overwrite handled by shadcn add)")
      return
    }
    log("⚠️", "shadcn add failed — falling back to direct copy of the panel primitives.")
  }

  const uiDir = join(target, "src", "components", "ui")
  for (const file of REQUIRED_PRIMITIVES) {
    copyFile(join(PRIMITIVES_SRC, file), join(uiDir, file), force, target)
  }

  copyFile(join(PRIMITIVES_SRC, "loading-button.tsx"), join(target, "src", "components", "loading-button.tsx"), force, target)

  const utilsDest = join(target, "src", "lib", "utils.ts")
  if (existsSync(utilsDest)) {
    const utils = readFileSync(utilsDest, "utf8")
    if (utils.includes("export function cn") || utils.includes("export const cn")) {
      log("•", `src/lib/utils.ts: already present (cn found)`)
    } else {
      log("⚠️", `src/lib/utils.ts exists but does not export cn(). Add a cn() function (clsx + tailwind-merge).`)
    }
  } else {
    copyFile(join(PRIMITIVES_SRC, "lib", "utils.ts"), utilsDest, true, target)
  }
}

function installDeps(target, pm) {
  const runner = pm ?? detectPackageManager(target)
  const args = ["add", ...RUNTIME_DEPS]
  log("⇣", `installing dependencies (${runner} ${args.join(" ")})`)
  const res = spawnSync(runner, args, { cwd: target, stdio: "inherit", shell: process.platform === "win32" })
  if (res.status !== 0) {
    log("⚠️", "Dependency install failed. Run the install command above manually.")
    return false
  }
  return true
}

function printNextSteps(target, framework, warnings) {
  const isVite = framework === "vite"
  log("", "")
  log("🚀", "Integration complete! Next steps:")
  if (isVite) {
    log("", `  1. import:  import { OneShotAiPanel } from "@/external-modules/ai-panel"`)
    log("", `  2. Use it in a client component: <OneShotAiPanel systemPrompt=... tickets=... adapter={...} />`)
    log("", `  3. Make sure src/index.css imports 'tailwindcss' + 'tw-animate-css' and defines the shadcn theme tokens.`)
    log("", `  4. No existing theme? import 'one-shot-ai-panel/theme.css' in your entry (main.tsx).`)
    log("", `  5. Configure the '@' alias → src (see warnings below if any).`)
    if (!args.noProxy) {
      log("", `  6. OpenCode Zen: wire the generated vite.zen-proxy.mjs into server.proxy (see the file header).`)
    }
  } else {
    log("", `  1. import:  import { OneShotAiPanel } from "@/external-modules/ai-panel"`)
    log("", `  2. Use it in a client component: <OneShotAiPanel systemPrompt=... tickets=... adapter={...} />`)
    log("", `  3. Make sure your globals.css imports 'tailwindcss' + 'tw-animate-css' and defines the shadcn theme tokens.`)
    log("", `  4. No existing shadcn setup? Use the theme template: copy the package's themes/globals.css as a base.`)
    if (!args.noProxy) {
      log("", `  5. OpenCode Zen is ready: the same-origin proxy was generated at <app>/api/zen/v1/[...path]/route.ts.`)
    }
  }
  if (warnings.length) {
    log("", "")
    log("⚠️", `${warnings.length} warning(s) to review before compiling:`)
    for (const w of warnings) {
      for (const line of w.split("\n")) log("", `  ${line}`)
      log("", "")
    }
  }
}

const args = parseArgs(process.argv.slice(2))

if (args.help) {
  help()
  process.exit(0)
}

const target = args.dir

if (!existsSync(join(target, "package.json"))) {
  process.stderr.write(`✗ No package.json found in ${target}\n`)
  process.exit(1)
}
if (!existsSync(join(target, "src"))) {
  process.stderr.write(`✗ No src/ directory found in ${target}. The panel requires a React/Next.js project with a src directory.\n`)
  process.exit(1)
}
if (!existsSync(MODULE_SRC) || !existsSync(PRIMITIVES_SRC)) {
  process.stderr.write(`✗ Module sources not found (corrupted package). Reinstall one-shot-ai-panel.\n`)
  process.exit(1)
}

log("", `Integrating OneShotAiPanel → ${target}`)
const moduleExists = existsSync(join(target, args.moduleDir))
if (args.moduleOnly || moduleExists) {
  installModule(target, args.force)
  installZenProxy(target, args.force)
  log("", moduleExists
    ? `Existing source-mode install detected in ${args.moduleDir} → module-only ${args.force ? "update" : "check"}. Use --force to overwrite.`
    : "module-only mode: ui/*, css and deps are left untouched.")
  process.exit(0)
}
const framework = detectFramework(target)
const viaRegistry = !args.noRegistry && detectShadcn(target)
installModule(target, args.force)
installZenProxy(target, args.force)
installPrimitives(target, args.force, viaRegistry)
const cssPath = !args.noCss ? patchGlobalsCss(target, args.force) : undefined
const warnings = []
if (cssPath) checkTailwind(cssPath, warnings)
checkAlias(target, framework, warnings)
if (!args.noInstall) installDeps(target, args.pm)
printNextSteps(target, framework, warnings)
